### ISSUE TITLE
check_for_openmp does not necessarily use the same compiler as cythonize

### ISSUE THREAD

**Issue by crocha700** [pyqg/pyqg#100]
Everything works fine on linux server with CentOS. But a Mac OS El Capitan with gcc installed from  [Mac-hpc](http://hpc.sourceforge.net), ```check_for_openmp``` uses ```clang``` whereas ```cythonize``` appears to use ```gcc```.

If we simply comment out that test in setup.py, 

```python
extra_compile_args = []
extra_link_args = []

use_openmp = True
#if check_for_openmp() and use_openmp:
#    extra_compile_args.append('-fopenmp')
#    extra_link_args.append('-fopenmp')
#else:
#    warnings.warn('Could not link with openmp. Model will be slow.')    

extra_compile_args.append('-fopenmp')
extra_link_args.append('-fopenmp')
```

then everything works.

**Comment by rabernat** [comment]
This sounds like it is related to path issues. 

I install the [mac hpc](http://hpc.sourceforge.net/) compilers into custom locations in ``/usr/local`` in order to keep them isolated (e.g. ``/usr/local/gcc-4.8``). They are not in my path.

When I compile pyqg with a non-default compiler, I always do it like this

```bash
CC=/usr/local/gcc-4.8/bin/gcc python setup.py build_ext --inplace
```

Could you just do ``which gcc`` and tell me what you get?

**Comment by crocha700** [comment]
```{bash}
crocha ~ $ which gcc
/usr/local/bin/gcc
```

**Comment by rabernat** [comment]
And that is the mac-hpc version?

**Comment by rabernat** [comment]
Could you also do ``which cc``?

**Comment by crocha700** [comment]
yes, that is the mac-hpc version. 

```{bash}
crocha ~ $ which cc
/usr/bin/cc

crocha ~ $ cc
clang: error: no input files

gcc: fatal error: no input files
compilation terminated.
```

**Comment by rabernat** [comment]
ok I think I know the problem

**Comment by jamesp** [comment]
I think this is very much dependent on which version of python you are using.  It seems that Cython changes the -W flags that are passed to `CC` depending on some version and platform specifics that I can't fathom.

On my computer I have tried several different setups with varying success.  Cython is definitely trying to do something clever in switching warning flags which is being confounded by manually overriding the compiler. e.g. `-Wshorten-64-to-32` is being passed when using the builtin python as it is expecting `cc` to be `clang`, other gcc implementations do not recognise this warning.

* *virtualenv using builtin mac python and pip and cc*
	Compiles without openmp

		jpimac:pyqg jp492$ python setup.py build_ext --inplace
		check_for_openmp() result:  1
		setup.py:117: UserWarning: Could not link with openmp. Model will be slow.
		  warnings.warn('Could not link with openmp. Model will be slow.')
		Compiling pyqg/kernel.pyx because it depends on pyqg/.compile_time_use_pyfftw.pxi.
		[1/1] Cythonizing pyqg/kernel.pyx
		running build_ext
		...
		kernel.so
		copying build/lib.macosx-10.10-intel-2.7/pyqg/kernel.so ->

* *using either homebrew gcc or hpc-gcc and builtin python*
	Does not compile

		jpimac:pyqg jp492$ CC=/usr/local/gcc-5.1/bin/gcc python setup.py build_ext --inplace
		check_for_openmp() result:  0
		Compiling pyqg/kernel.pyx because it depends on pyqg/.compile_time_use_pyfftw.pxi.
		[1/1] Cythonizing pyqg/kernel.pyx
		running build_ext
		building 'pyqg/kernel' extension
		/usr/local/gcc-5.1/bin/gcc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -arch i386 -pipe -I/Users/jp492/envs/python/pyqg/lib/python2.7/site-packages/numpy/core/include -I/System/Library/Frameworks/Python.framework/Versions/2.		nclude/python2.7 -c pyqg/kernel.c -o build/temp.macosx-10.10-intel-2.7/pyqg/kernel.o -fopenmp
		gcc: error: unrecognized command line option ‘-Wshorten-64-to-32’
		error: command '/usr/local/gcc-5.1/bin/gcc' failed with exit status 1

* *using conda python and homebrew gcc or hpc-gcc*
Compiles with warnings.

		jpimac:pyqg jp492$ source activate pyqg
		discarding /Users/jp492/.miniconda3/bin from PATH
		prepending /Users/jp492/.miniconda3/envs/pyqg/bin to PATH
		(pyqg)jpimac:pyqg jp492$ CC=/usr/local/gcc-5.1/bin/gcc python setup.py build_ext --inplace
		check_for_openmp() result:  0
		Compiling pyqg/kernel.pyx because it depends on pyqg/.compile_time_use_pyfftw.pxi.
		[1/1] Cythonizing pyqg/kernel.pyx
		running build_ext
		...
		/usr/local/gcc-5.1/bin/gcc -bundle -undefined dynamic_lookup -L/Users/jp492/.miniconda3/envs/pyqg/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.5-x86_64-2.7/pyqg/kernel.o -L/Users/jp492/.miniconda3/envs/pyqg/lib -o build/lib.macosx-10.5-x86_64-2.7/pyqg/kernel.so -fopenmp
		ld: warning: could not create compact unwind for ___pyx_pf_4pyqg_6kernel_20PseudoSpectralKernel__kernel_init: stack subq instruction is too different from dwarf stack size
		copying build/lib.macosx-10.5-x86_64-2.7/pyqg/kernel.so ->

All this said, it seems that the most stable setup is to use Anaconda and I suppose new users should be encouraged to go in that direction.  You already have good documentation on pyqg homepage for installing pyfftw with conda.

For those interested,

		brew install gcc --without-multilib --with-fortran

should get you a version off `gcc` with openmp support.
I'm not sure how this differs from the HPC version as I can't see anywhere on the website the flags he used to compile those versions.  I don't really like that the HPC documentation suggests to just `tar -xvf gcc-5.1-bin.tar -C /`, @rabernat's solution of putting in `/usr/local/gcc-5.1` is more easily reversible.

Is it worth documenting any of this on the installation page?

**Comment by rabernat** [comment]
@jamesp - just a quick question before diving into your issue: are you using the latest master, which incorporates the fix #101?

**Comment by jamesp** [comment]
I am using the version without this change as I haven't updated my fork (oops) but it shouldn't make a difference.  `gcc` still points to `clang` in a basic setup, and in the other cases where I am specifying env var `CC` that line of code changed in #101 won't be evaluated.

If a new user doesn't mind having not having openmp then all of this is moot, the test fails and the kernel compiles successfully without the openmp library.  But if the new user does want openmp and tries to compile with another version of `gcc` there is potential for compilation to fail again, and it's not obvious why.

**Comment by jamesp** [comment]
I'm not sure that my issue above can necessarily be 'fixed' - there are too many potential differences in environment setup to get it right for all cases.  Documenting a case that we know works for Mac OSX users (i.e. conda and HPC gcc) might be sufficient.

**Comment by rabernat** [comment]
@jamesp - can you run the following commands for your setup?
```bash
$ which cc
$ which gcc
```

**Comment by jamesp** [comment]
jpimac:~ jp492$ which gcc
	/usr/bin/gcc
	jpimac:~ jp492$ which cc
	/usr/bin/cc
	jpimac:~ jp492$ gcc --version
	Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
	Apple LLVM version 7.0.0 (clang-700.1.76)
	Target: x86_64-apple-darwin14.5.0
	Thread model: posix
	jpimac:~ jp492$ cc --version
	Apple LLVM version 7.0.0 (clang-700.1.76)
	Target: x86_64-apple-darwin14.5.0
	Thread model: posix

**Comment by crocha700** [comment]
Maybe we can hack setup.py to include the compiler's path. From the [cython's docs](http://docs.cython.org/src/reference/compilation.html):

>If you need to specify compiler options, libraries to link with or other linker options you will need to >create Extension instances manually (note that glob syntax can still be used to specify multiple >extensions in one line):

```{python}
from distutils.core import setup
from distutils.extension import Extension
from Cython.Build import cythonize

extensions = [
    Extension("primes", ["primes.pyx"],
        include_dirs = [...],
        libraries = [...],
        library_dirs = [...]),
    # Everything but primes.pyx is included here.
    Extension("*", ["*.pyx"],
        include_dirs = [...],
        libraries = [...],
        library_dirs = [...]),
]
setup(
    name = "My hello app",
    ext_modules = cythonize(extensions),
)
```

**Comment by MFJansen** [comment]
Sorry guys, I'm trying to catch up:
Is it generally agreed on that the model doesn't compile with clang 
If so is that something we can fix?
(It seems like that would make a lot of people's life easier)

**Comment by jamesp** [comment]
@MFJansen If you want openmp support, you can't use clang compilers that come with OSX as standard.

If you are happy to run without openmp, then the fix @rabernat put in above will now allow compilation with clang on OSX without error.

My experimentation suggests that getting a configuration that compiles with openmp support depends on interactions between gcc and cython and appear to be platform specific.  Perhaps it is only me that hit this issue because I used the builtin python instead of conda?  Whatever the case, I agree it should be documented.  As the docs already recommend that users install Anaconda, we should also document the HPC gcc compiler or the homebrew version.

Have you guys previously profiled the speedup openmp gives?  Anecdotally, I don't see orders of magnitude difference when running the examples with and without it.  But I'm new to parallel processing, I'm not sure at what scale I should expect to see performance gains.

**Comment by jamesp** [comment]
Proposed update to Installation doc in #106
