### ISSUE TITLE
make demo repo for binder

### ISSUE THREAD

**Issue by rabernat** [pyqg/pyqg#104]
This is so cool:
http://mybinder.org/

**Comment by crocha700** [comment]
Very cool. 

We could also have a gallery of examples that reproduce seminal papers. For example, here's an attempt to reproduce [Larichev and Held 1995](http://git.io/vW7De) (This needs to run ten longer to equilibrate and reproduce the other figures with diagnostics, but you you get the idea.) 

Not sure many real examples be able to run my binder, though. But this gallery of example would help Geoff and others I talked to here at Scripps that are willing to use pyqg for teaching.

**Comment by rabernat** [comment]
How awesome would it be: an online gallery of reproducible classic results in geophysical turbulence!

We could write a paper about that in BAMS...

**Comment by francispoulin** [comment]
I agree that it's a great contribution and people would really love that.  Should also help people to get into the field to actually see the simulations, rather than just imagine it. As a lot of us did.

**Comment by crocha700** [comment]
This is how this would work (I had to implement this on [my fork](https://github.com/crocha700/pyqg) since apparently this only works on branch master). You can launch the binder by clicking on [launch | binder](http://mybinder.org/repo/crocha700/pyqg)

I could run the examples from my cellphone!

**Comment by francispoulin** [comment]
That is pretty incredible.  Unlike many systems it is actually portable.  I will have to learn how this works.

**Comment by rabernat** [comment]
I tested binder out with the Larichev and Held example.

It was very slow to execute and didn't finish the calculation by the time the binder instance expired. (It is not using pyfftw, so there is definitely more optimization that could be done.)

While cool in principle, our simulations might be a little too computationally expensive to run for free in the cloud.

**Comment by crocha700** [comment]
> While cool in principle, our simulations might be a little too computationally expensive to run for free in the cloud

Agreed. Two-layer example and other simple simulation still run well. More costly simulations could be available to be forked by users.

**Comment by jamesp** [comment]
This seems similar to the work the Jupyter team have been doing.  See http://tmpnb.org which has the source available here https://github.com/jupyter/tmpnb.

Last year I tried to set something up based on tmpnb for an examples class.  It was just a little too janky to get it to work reliably back then, but it may be better now.  I love the concept, especially for teaching and disseminating ideas.  I believe tmpnb was originally developed for this Nature article http://www.nature.com/news/interactive-notebooks-sharing-the-code-1.16261

**Comment by rabernat** [comment]
If anyone (@jamesp?) is motivated to work on this, it would be great to try to tune the binder examples to a manageable size which can run in a reasonable amount of time yet still show something cool.

**Comment by crocha700** [comment]
Here's an idea: publish notebooks to (gallery)[https://github.com/pyqg/pyqg_gallery]. This notebooks can be rendered by nbviewer, but must but forked/download and executed locally. And publish small size notebooks to [demos](https://github.com/pyqg/pyqg_demos). The binder would be associated with the latter.

@jamesp it would be great if you could work with Geoff to come up with some examples that are associated with discussions and exercises in his book.  I have other core priorities for pyqg now, but I'm glad to assist if you take the lead.

**Comment by jamesp** [comment]
Sure, happy to give it a go.  I've discussed with Geoff creating some workshops to go along with the course he teaches here, that might be a good place to start.

A good way for me to get familiar with pyqg too, beyond just the install process!

**Comment by jamesp** [comment]
@crocha700 Great idea.  I'll speak with Geoff tomorrow, I'm sure he'll be keen.  I'll start looking at it, will give you a shout as I get stuck...

**Comment by rabernat** [comment]
> would be great if you could work with Geoff to come up with some examples that are associated with discussions and exercises in his book.

:+1: :+1: :+1: 

If we can link pyqg to Geoff's book, it will blow up.

Long term goal is to write a paper for BAMS or equivalent describing pyqg, why we made it, what role it can have in teaching and research, etc. We need to really play up the open-source / reproducibility angle.

**Comment by crocha700** [comment]
>@crocha700 Great idea.  I'll speak with Geoff tomorrow, I'm sure he'll be keen.  I'll start looking at it, will give you a shout as I get stuck...
Great! 

>Long term goal is to write a paper for BAMS or equivalent describing pyqg, why we made it, what role it can have in teaching and research, etc. We need to really play up the open-source / reproducibility angle.
:+1:

**Comment by crocha700** [comment]
I updates the [demos](https://github.com/pyqg/pyqg_demos)  and [gallery](https://github.com/pyqg/pyqg_demos) to get things started. 

I could run the two examples in the [cloud](http://mybinder.org/repo/pyqg/pyqg_demos) in less than 5 minutes.  Formatting and discussion is still poor, but it's a start. Further discussions can be taken on those repos.
