### ISSUE TITLE
Cesar is working on pyqg on Saturday night

### ISSUE THREAD

**Issue by rabernat** [pyqg/pyqg#110]
@MFJansen @francispoulin @crocha700 I'm afraid we have created a monster! :japanese_ogre:

**Comment by francispoulin** [comment]
If there was a way to like this comment I would.

**Comment by MFJansen** [comment]
And not just any Saturday night - Halloween! 😱

**Comment by MFJansen** [comment]
ps: I like how this is officially an "issue" now
