### ISSUE TITLE
benchmarks

### ISSUE THREAD

**Issue by francispoulin** [pyqg/pyqg#114]
Has anyone run the benchmarks lately? Yesterday I updated to the latest version and decided for fun that I would run the benchmarks.    It has been more than 12 hours and it's now on the 2048 test. 

Also, from what I gather with the results, the openMP is slightly faster but you need a pretty big grid for it to be worthwhile.  If this saves the data to a file I am happy to share it, if/when it finishes.

**Comment by rabernat** [comment]
> Has anyone run the benchmarks lately? Yesterday I updated to the latest version and decided for fun that I would run the benchmarks. It has been more than 12 hours and it's now on the 2048 test.

How many cores does your system have? The benchmark script is extremely comprehensive. If you are on a laptop, I am not surprised it takes that long.

> Also, from what I gather with the results, the openMP is slightly faster but you need a pretty big grid for it to be worthwhile.

It is important to distinguish between multithreading pyfftw (does not require openmp) and the openmp-based parallel optimizations I made in the cython kernel. My hunch is that the openmp speedup is quite minimal, since the ffts take up all of the compute time. It would be good to benchmark these separately actually, but currently the code does not permit that.

**Comment by francispoulin** [comment]
My laptop has 4 cores.  Nothing fancy but it was all that 4 years ago.  

Right now it started the 2048 case and for 1 thread(?) it took almost 9 hours.  

The 1024 case with 1 thread took less than an hour.  I wonder whether we should change the default to stop at 1024?  That might be enough.

I was hoping to use this to get a feeling as to how the threads work in speeding things up, if they do.

For 1024 with 1,2,4,8,16,32 threads I get the following times in hours:

0.88305556,  0.6525    ,  0.57194444,  0.5575    ,  0.55416667,    0.54388889

Because my machine has a quadcore processor, I didn't expect it go do much better beyond 4.  But even going from 1 to 2, there is only marginal improvement. 

I will try and do the same thing on my desktop that has 2x8 cores and see how that does.

**Comment by rabernat** [comment]
Definitely post your full results. Mine are here:
http://nbviewer.ipython.org/gist/rabernat/5144ad82a1cc9edb8961

**Comment by francispoulin** [comment]
Ok, I will do that.  

I like your script and see that it reads the data from a csv file.  Unfortunately, we don't have an option to do that in the benchmark.  I am useful when it comes to csv but can try and figure out how to safe the results and then read it in.

**Comment by francispoulin** [comment]
Thanks @rabernat for the link.  It helped introduce me to pandas.  Seems nice but I do have a lot to learn.  Since I thought it might be nice to keep things consistent, I am trying to modify the benchmark script so that it saves a csv file and then we can read it in later, to compare on different machines.

All I've done is I've defined an array with the times and then store this in a DataFrame.

        data[j,i] = tottime

df = pd.DataFrame(data, index=mynx, columns=mynth)
df.to_csv("benchmark.csv",  skipinitialspace=True)

When I read reading it in using read_csv, I get the array in d but I'm not sure how to access a row or column.  I tried the syntax in your example using pivot but that didn't work.

d = pd.read_csv('benchmark.csv')

Could you show me how to access a row?  Then it should be easy enough to plot the results, like you did.

**Comment by rabernat** [comment]
@francispoulin: all you have to do to get the results of ``benchmark.py`` into a csv file is to pipe its output to a file from the command line

```bash
python benchmark.py > results.csv
```

**Comment by francispoulin** [comment]
Wow!  That is so much easier than what I was trying to do and works beautifully.  Thanks @rabernat .

**Comment by francispoulin** [comment]
Ok, I now have a benchmark on my laptop.  There seems to be some marginal speed up with 2 cores but not much beyond that.  Tomorrow I will try and set up something similar on my desktop.  

https://gist.github.com/francispoulin/feae548d9a3551372760
