### ISSUE TITLE
pysw?

### ISSUE THREAD

**Issue by francispoulin** [pyqg/pyqg#122]
This week I want to create the foundations of a new github repository called pysw.  Basically, this is a shallow water version of pyqg.  Before I do anything I wanted to ask the pyqg creates a couple of questions.

First, would you mind if I used what we have as pyqg as a skeleton?  I plan to copy what we have because I think it's really great and modify the equations.   I know that pyqg is open source and that anyone can take anything and use it, within the confines of the MIT license (thanks to @rabernat ).  But at the same time I think it would be rude if I didn't ask you all for your permission since you've put so much effort into it already.

One thought that I had was to have this as a subset of pyqg but I think that will make things too constraining for me and thought this would be easier.

Second, who would be interested in helping to develop this?  By that I mean, would you like to have administration access to the github repo?  

I have the equations coded up on a variety of other codes and don't *think* it will be a lot of work and would certainly appreciate your input and contributions.  

One of the reasons for doing this sooner rather than later is that Geoff was asking whether this would exist before January, when he teaches a course.  I want to have a version in the next month or so that he can start using it.  

@jamesp , since you are working with Geoff, would you be interested in maybe doing some tests as things develop?

I hope that this will help to accomplish some of what pyqg does, 1) reproduce classical results and 2) let people simulate things on their own, but for problems that qg does not apply to.  By that I mean with gravity waves and not so small Rossby numbers.

As usual, your thoughts/comments are greatly appreciated.

**Comment by crocha700** [comment]
Not sure this should be a `pyqg` issue. At any rate, I'd be interested in be involved, though this would not be a short-term priority for me.

Incidentally, yesterday I created a new organization called [pyboussinesq](https://github.com/pyboussinesq), under which I pushed a [script](https://github.com/pyboussinesq/TwoDimBoussinesq) I crafted during the Summer to solve the 2D (x-z) Boussinesq equations with a background stratification (an afternoon hack to solve a strongly-stratified shear-instability problem). My academic sibling @glwagner has the idea of turning this into a bigger project. The main motivation is to study breaking internal  gravity waves. That project is not my priority either. @glwagner  is taking the lead, but everybody is welcome to join us.

**Comment by francispoulin** [comment]
Sorry @crocha700 for the social faux pas.  I probably have just written you all an email.

Thanks for mentioning your new project.  A few months ago I wrote a spectral 2D Boussinesq solver to solve the convection problem.  Sounds like you are solving the same system but with a more sophisticated set up.  I will certainly follow how this progresses.

**Comment by rabernat** [comment]
@francispoulin You don't need anyone's permission to do this! Just start coding!

**Comment by francispoulin** [comment]
Thanks @rabernat
