### ISSUE TITLE
Error when running examples: No attribute 'Hi'

### ISSUE THREAD

**Issue by bielim** [pyqg/pyqg#140]
When running example 2 (the barotropic model) and 3 (the surface QG model) I get an error in m.run_with_snapshots due to a non-existent attribute 'Hi' (see attached screenshots).
![btmodel_no_attr_hi](https://cloud.githubusercontent.com/assets/10673070/14036960/e628185e-f214-11e5-87dd-d6b9e23a658b.png)
![sqgmodel_no_attr_hi](https://cloud.githubusercontent.com/assets/10673070/14036961/eb88faac-f214-11e5-825a-7de3b33e223b.png)

**Comment by crocha700** [comment]
Thanks for point that out @bielim!
