### ISSUE TITLE
program doesn't terminate correctly in python 3.5

### ISSUE THREAD

**Issue by rabernat** [pyqg/pyqg#142]
Intermittently, python 3 does not exit correctly after running pyqg. This causes some travis-ci builds to fail because the [test script never exits and eventually times out](https://travis-ci.org/pyqg/pyqg/jobs/118678139).

I have no idea how to fix this. I vaguely suspect it has something to do with [memory allocation / deallocation in cython](http://docs.cython.org/src/userguide/special_methods.html#finalization-method-dealloc).

To reproduce:

``` bash
# creates a python 3.5 environment with pyfftw called test_env
conda env create -f ci/environment-py35-pyfftw.yml
source activate test_env
python setup.py build_ext --inplace
pip install -e .
# repeat this line a few times; eventually it will hang instead of terminating the python process
python -c 'import pyqg; m = pyqg.QGModel()'
```

**Comment by asross** [comment]
I'm guessing this is resolved by upgrades.
