### ISSUE TITLE
Automatic / Adaptive Timestepping

### ISSUE THREAD

**Issue by rabernat** [pyqg/pyqg#144]
Currently the timestep is set manually. This is both a challenge for novice users (how do you know how to pick) and a major performance bottleneck (if the timestep is unnecessarily small). 

We should make the timestep choice automatic based on a target CFL condition. I found some nice documentation about how to do this with Adams Bashforth.

http://lucan.me.jhu.edu/wiki/index.php/The_flow_solver_implementation#Adaptive_time_stepping
http://lucan.me.jhu.edu/wiki/index.php/Second-order_variable_time_step_Adams-Bashforth_method

**Comment by rabernat** [comment]
@crocha700, @MFJansen -- do you have any thoughts about adaptive timestepping?

@anirban89 and I are doing some simulations where we really don't know what the equilibrated KE will be, and we are having a hard time guessing the right timestep. Too small and it takes forever, too large and CFL blows up.

What have you been doing about this?

**Comment by crocha700** [comment]
Quick-and-dirty solution: start with a fraction (perhaps 1/10?) of the time-scale of the most linearly unstable mode. You can then test the CFL number every once in a while, and reduce the time-step if the CFL number  is too large --- one way to test if this is effective without messing up with the kernel/model class is to use ``run_with_snapshots''.

Long-term-solution: Implement more robust time-steppers and use an automatic approach as you suggest above.

**Comment by rabernat** [comment]
> You can then test the CFL number every once in a while, and reduce the time-step if the CFL number is too large

This is what we had in mind, but the code as is doesn't actually allow you to change the timestep once the kernel is initialized. So we will at least have to implement that.

**Comment by MFJansen** [comment]
I don't have much to add. Yes, an adaptive time step which periodically re-calculates the time step based on a CFL criterion would be a good addition. From an algorithmic point of view this seems pretty straightforward (although as @rabernat points out above you have to be little bit carefull with the A-B time-stepping). I'm obviously a bit behind on the Kernel implementation. Why can't we change the time-step in the Kernel? Isn't it a model attribute?

**Comment by rabernat** [comment]
> Why can't we change the time-step in the Kernel? Isn't it a model attribute?

The kernel uses a hidden attribute called `._dt` to store the timestep, while the python level uses a different variable `.dt`. This is stupid and there is no good reason for it, just me making the code unnecessarily complicated.
