### ISSUE TITLE
QGmodel diagnostics

### ISSUE THREAD

**Issue by anirban89** [pyqg/pyqg#149]
for the diagnostic 'APEgenspec', line 268 reads 
`np.real(1j*self.k*(self.del1*self.ph[0] + self.del2*self.ph[0]) *`
Instead it should probably be
`np.real(1j*self.k*(self.del1*self.ph[0] + self.del2*self.ph[1]) *`

**Comment by crocha700** [comment]
Thanks @anirban89!

For the record, this was introduced is this [refactoring](https://github.com/pyqg/pyqg/commit/7be1ef6c2c2e7621eaf2bc1e543c8511935fb597) back in May 2015.  

Will you submit a PR or should I take care of this?

ps: You can use the the ``layered_model`` class to perform 2 layer calculations.
