### ISSUE TITLE
nanshe/pyfftw does not seem to exist anymore

### ISSUE THREAD

**Issue by roxyboy** [pyqg/pyqg#163]
The nanshe channel (recommended in the installation documentation: http://pyqg.readthedocs.io/en/stable/installation.html) does not seem to support pyfftw anymore. After running the following, I got an error message.
```
$ conda install -c nanshe pyfftw
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ......
Solving package specifications: .
Error:  Package missing in current linux-64 channels: 
  - pyfftw

You can search for this package on anaconda.org with

    anaconda search -t conda pyfftw
```

I installed pyfftw from the conda-forge channel instead.

**Comment by glwagner** [comment]
I think pyfftw is now available through pip. Does ```pip install pyfftw``` work for you?

**Comment by roxyboy** [comment]
I like to use conda instead of pip to keep the PATHs consistent.

**Comment by rabernat** [comment]
It is available through the conda-forge channel:
https://github.com/conda-forge/pyfftw-feedstock

**Comment by rabernat** [comment]
And this is what we use in our own travis CI environment:
https://github.com/pyqg/pyqg/blob/master/ci/environment-py27-pyfftw.yml

**Comment by rabernat** [comment]
The documentation should be fixed in my latest PR.
