### ISSUE TITLE
Install issue "AttributeError: class Extension has no attribute '__mro__'"

### ISSUE THREAD

**Issue by braaannigan** [pyqg/pyqg#165]
When installing the pyqg dependencies I got the error "AttributeError: class Extension has no attribute '__mro__'" when I ran pip install pyqg.

This turns out to be an issue with Cython 0.25.  It was resolved for the me by using the previous version of Cython 
pip install 'cython<0.25.0' 
and then running pip install pyqg again.

**Comment by rabernat** [comment]
but it would be good for pyqg to be compatible with the latest version of cython.

Could you post a more detailed trace of the error?

**Comment by braaannigan** [comment]
I don't have the original trace.  I've tested installation with new python 2.7 and 3.6 environments. Installation goes smoothly so it might have been something specific to the environment I'd been using with a lot of packages on it.
