### ISSUE TITLE
a quick question

### ISSUE THREAD

**Issue by ruishi00** [pyqg/pyqg#166]
Dear all:

New to QG dynamics. Thanks in advance for your help!

I tried to run the 2-layer version of the code, and set beta to zero. Isn't this going to get rid of any PV gradient?

rs

**Comment by rabernat** [comment]
No. You will still have a PV gradient due to the geostrophic shear. See equations 9 and 10 here
http://pyqg.readthedocs.io/en/latest/equations/notation_twolayer_model.html

To completely eliminate the PV gradient in the two layer model, you also need to set U2 = U1.

**Comment by ruishi00** [comment]
Thank you so much!
