### ISSUE TITLE
pyqg installation error via Mac terminal

### ISSUE THREAD

**Issue by dylangaeta** [pyqg/pyqg#172]
I tried to install `pyqg` via the terminal using:
`git clone https://github.com/pyqg/pyqg.git`

and then I `cd`'d to the `pyqg` directory and installed via the command:
`python setup.py install`

It appeared to install correctly, according to the text in the terminal, but when I ran my Python script with `import pyqg`, I ran into an error, shown in the attached screenshot. 

I was able to get around this error by doing the following: 

1) I re-cloned the github package.
2) Before the `python setup.py install` command, I opened `model.py` (found inside the second "pyqg" folder) and deleted `tendency_forward_euler` from the `import` command on line 8. `tendency_forward_euler` doesn't get used in the subsequent code (it's commented out in `model.py`) so this shouldn't cause any further problems. 
3) Then inside the first "pyqg" directory, I tried `python setup.py install` again, and then everything worked. I was able to `import pyqg` in my script, and the model ran the examples fine

For reference, I also had an error that looked like this at one point: 
```
`ImportError `                             ` Traceback (most recent call last)`
<ipython-input-10-5a9fd8ee2929> in <module>()
      2 import matplotlib.pyplot as plt
      3 get_ipython().run_line_magic('matplotlib', 'inline')
----> 4 import pyqg

~/anaconda3/lib/python3.6/site-packages/pyqg/__init__.py in <module>()
      1 __version__='0.1.3'
----> 2 from .model import Model
      3 from .qg_model import QGModel
      4 from .bt_model import BTModel
      5 from .sqg_model import SQGModel

~/anaconda3/lib/python3.6/site-packages/pyqg/model.py in <module>()
      3 from numpy import pi
      4 import logging
----> 5 from .kernel import PseudoSpectralKernel, tendency_forward_euler, tendency_ab2, tendency_ab3
      6 try:
      7     import mkl

ImportError: dlopen(/Users/me/anaconda3/lib/python3.6/site-packages/pyqg/kernel.cpython-36m-darwin.so, 2): Symbol not found: _GOMP_parallel
  Referenced from: /Users/dylangaeta/anaconda3/lib/python3.6/site-packages/pyqg/kernel.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/dylangaeta/anaconda3/lib/python3.6/site-packages/pyqg/kernel.cpython-36m-darwin.so
```

<img width="1094" alt="pyqg_error" src="https://user-images.githubusercontent.com/28328874/38277276-7d7f2f6e-375d-11e8-9d14-68156140ba84.png">

**Comment by asross** [comment]
Hopefully resolved by https://github.com/pyqg/pyqg/pull/278.
