### ISSUE TITLE
Some problems in code

### ISSUE THREAD

**Issue by gmuxu** [pyqg/pyqg#174]
I just try to reproduce the code and I found three problems in the code and document.
1. In the doc, I think there is a missing negative sign in the second equation at "Equation in the Fourier space" section.
2. In the doc, it doesn't mention background zonal velocity in the primitive equations. This term is really important in the calculation.
3. In the doc, $F_1=\frac{k_d^2}{1+\delta^2}$ while $F_1=\frac{k_d^2}{1+\delta}$ in the code. I am kind of confused about this.

**Comment by MFJansen** [comment]
Hi @buaamuxu,
Thanks for pointing these out! Re 3: The code is right, the documentation is wrong. All the issues therefore seem to be with the documentation, not with the code. But yes, the documentation of the two-layer QG equations clearly needs some fixing.
