### ISSUE TITLE
Inversion relation for SQG and barotropic deformation radius

### ISSUE THREAD

**Issue by benmayersohn** [pyqg/pyqg#178]
Hi all,

I just started playing around with pyqg (love it!) and think I've stumbled upon two issues:

1) The barotropic deformation radius (self.radii[0]) is computed as self.g * self.H / f, and I think you meant to square root the numerator.

2) I think there's a error in the inversion relationship between buoyancy (b) and the streamfunction (psi) in the SQG model. If I'm not mistaken, it implies that hat(psi) = N/K * hat(b), but I think it should be 1/(NK) * hat(b). For the example scenario you presented from the Held et al (1995) paper, Nb was set to 1 so it would have had no effect on the solution.

Thanks!

**Comment by rabernat** [comment]
Thanks for this bug report @benmayersohn and sorry no one ever replied to you.

I think (1) is the same is #185 and should have been fixed by #186. Could you confirm?

The SQG issue remains. Would you be interested in submitting a pull request to fix it?

**Comment by MFJansen** [comment]
The SQG inversion issue seems to be related to a fix implemented by @rochanotes on the original code of @francispoulin (https://github.com/pyqg/pyqg/commit/4e172389f00e63fbcc80c25b23ea36f61ed18cd9#diff-185bed9bd30878a6745f6aa3ea9fa19b). Can you two have a look at this?
