### ISSUE TITLE
Installing pyqg on windows,about ‘pip install pyqg’

### ISSUE THREAD

**Issue by QimengLiu** [pyqg/pyqg#179]
Hello:
I'm trying to install pyqg on a Windows 10 system. I followed the first instructions and can import pyfftw successfully in python. However, when installed pyqg,I met some following error:

Command‘python setup.py egg-info’failed with error code 1 in C:\Users\lqm\AppData\Local\Temp\pip-install-ns8f8981\pyqg

I have no idea to fix it.Is there solution to this problem?

**Comment by a976187704** [comment]
Hello:
 Liu ,i have met the same question,have you figure it out

**Comment by QimengLiu** [comment]
> Hello:
> Liu ,i have met the same question,have you figure it out

Oh , I'm sorry for replying so late. No,I did not figure it out.If you have solution to this question, could you help me?

**Comment by asross** [comment]
Hopefully resolved (and not worsened) by https://github.com/pyqg/pyqg/pull/278.
