### ISSUE TITLE
Error about installing pyqg on windows

### ISSUE THREAD

**Issue by QimengLiu** [pyqg/pyqg#180]
When I install PYQG on terminal ,I met some following problem:

C:\Users\24593>pip install pyfftw
Collecting pyfftw
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))': /simple/pyfftw/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))': /simple/pyfftw/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))': /simple/pyfftw/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))': /simple/pyfftw/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))': /simple/pyfftw/
  Could not find a version that satisfies the requirement pyfftw (from versions: )
No matching distribution found for pyfftw

and then , I change the code: C:\Users\24593>pip install pyqg -i https://pypi.douban.com/simple

but I failed again

Looking in indexes: https://pypi.douban.com/simple
Collecting pyqg
  Downloading https://pypi.doubanio.com/packages/f8/bb/27916341f732a304b53a4618f42aab47f4c67d2b9e2d4a3b1eb7eb7b5cfe/pyqg-0.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\24593\AppData\Local\Temp\pip-install-h4_duixj\pyqg\setup.py", line 115, in <module>
        if check_for_openmp() and use_openmp:
      File "C:\Users\24593\AppData\Local\Temp\pip-install-h4_duixj\pyqg\setup.py", line 103, in check_for_openmp
        stdout=fnull, stderr=fnull)
      File "c:\users\24593\appdata\local\continuum\anaconda3\lib\subprocess.py", line 304, in call
        with Popen(*popenargs, **kwargs) as p:
      File "c:\users\24593\appdata\local\continuum\anaconda3\lib\subprocess.py", line 756, in __init__
        restore_signals, start_new_session)
      File "c:\users\24593\appdata\local\continuum\anaconda3\lib\subprocess.py", line 1155, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] 系统找不到指定的文件。

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\24593\AppData\Local\Temp\pip-install-h4_duixj\pyqg\

I have no idea how to fix it!

**Comment by rabernat** [comment]
Hi @QimengLiu - thanks for reporting this issue. I believe the best way to fix it is to provide a conda-forge build for pyqg.

**Comment by asross** [comment]
Hopefully this has been resolved by https://github.com/pyqg/pyqg/pull/278, feel free to reopen if not.
