### ISSUE TITLE
model.py

### ISSUE THREAD

**Issue by mnkmishra02** [pyqg/pyqg#185]
In model.py using vertical modes the radii[0] is wrong

**Comment by rabernat** [comment]
Hi @mnkmishra02 - thanks for your report, and welcome to the pyqg community! :)

Could you elaborate a bit on this issue? How did you reach this conclusion? Is the theory we are using wrong (https://pyqg.readthedocs.io/en/latest/equations/notation_verticalmodes.html), is this some sort of bug in the code?

**Comment by rabernat** [comment]
Is this the code you are referring to?

https://github.com/pyqg/pyqg/blob/4f41584a12bcbf8657785b8cb310fa5065ecabd1/pyqg/model.py#L247-L248

**Comment by mnkmishra02** [comment]
radii[0] = np.sqrt(self.g*self.H)/np.abs(self.f)

**Comment by rabernat** [comment]
Hi @mnkmishra02 - thanks for your reply to my question! :)

I'm not sure I understand your response. What does the expression
```
radii[0] = np.sqrt(self.g*self.H)/np.abs(self.f)
```
mean in this context? Is this what you think should be the correct value of radii for the model with vertical modes?

In general, if you could be a bit more verbose it would help our communication to converge more quickly.

**Comment by MFJansen** [comment]
Why was this closed? 

I'm not really familiar with this part of the code, but it looks to me like @mnkmishra02 is correct: radii[0] should simply be the barotropic deformation radius, i.e. radii[0] = np.sqrt(self.g*self.H)/np.abs(self.f).

The same issue has also been pointed out by @benmayersohn in issue#178. If whoever wrote this piece of the code can confirm that we are not missing anything and make the fix, that would be great!

**Comment by pittwolfe** [comment]
I have created #186 to address this.
