### ISSUE TITLE
Advection tests without FFTW aways fail.

### ISSUE THREAD

**Issue by pittwolfe** [pyqg/pyqg#189]
Pending pull requests are getting marked as failing CI tests because the advection tests aways fail for environments that don't include FFTW (i.e., py35 instead of py35-fftw). Considering that FFTW is a requirement for PyQG, I suggest we ditch the tests that don't include FFTW. All it's doing is consuming resources pointlessly (since we already know the code requires FFTW) and making it look like the contributions in the pull requests are doing something bad to the model.

**Comment by rabernat** [comment]
Christopher, thanks for looking into this!

The idea here is that pyqg does work without FFTW. In that case it falls back on numpy for ffts. Ideally we should fix the broken tests but not eliminate this option altogether.
