### ISSUE TITLE
Update APE diagnostics for non-uniform flow

### ISSUE THREAD

**Issue by mbueti** [pyqg/pyqg#196]
Spun off from #192, APEgenspec as currently formulated is not valid for background flows that are not uniform in a single layer.

We now throw an exception when users attempt to access APEgenspec, but this diagnostic (and likely other APE diagnostics) should be modified to accommodate structured Ubg.

**Comment by MFJansen** [comment]
Unfortunately, it looks to me like there may be some deeper issues with the non-uniform background flow implementation. If we want an explicit non-uniform background flow (and I'm still not sure how much sense that actually makes in the non-linear model, as I brought up in #159) the advection terms involving the background flow/PV gradient would need to be re-written via products taken in real space. I haven't gone through the full code but it seems like this is not done for the advection of background PV, which is still formulated as a linear term (ikQy*ph) in the kernel. Am I misunderstanding something?

**Comment by rabernat** [comment]
@worthamc has looked into this carefully. He identified the same bug.

**Comment by mbueti** [comment]
@MFJansen let me look back over #159, and the discussion there. In the kernel itself, yes, background PV is introduced as a linear term when the pv tendency is overwritten in do_advection. If we think it's worth keeping this feature, I can 100% look at reformulating how the BG PV gradient is introduced

**Comment by mbueti** [comment]
One slight correction: the non-uniform Ubg is also introduced in the uqh term  (lines 344 & 359 of kernel.pyx)

**Comment by MFJansen** [comment]
@mbueti, it seems that the varying background flow implementation generated a lot of unforeseen issues, so we decided to roll it back for now. We are certainly still interested in it if you want to pursue this further, but it seems like it would need more development and testing, before it can be merged back into the master branch.
