### ISSUE TITLE
module 'versioneer' has no attribute ‘get_version’

### ISSUE THREAD

**Issue by YONGQUAN-QU** [pyqg/pyqg#216]
I'm trying to upgrade pyqg to 0.3.0 after installing versioneer. 
It seems like there is an error

 "Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-hmbw2nb3/pyqg/setup.py", line 143, in <module>
        version=versioneer.get_version(),
    AttributeError: module 'versioneer' has no attribute 'get_version'
    check_for_openmp() result:  0"

I wondered how to fix the problem. Thank you very much

**Comment by navidcy** [comment]
+1 -- same problem here.

Btw, why one needs to install `versioneer`package independently? Can't `versioneer` be included in pyqg's dependencies?

**Comment by uegajde** [comment]
i find the reason.
somehow the file on pypi lacks the versioneer.py
https://github.com/pyqg/pyqg/blob/master/versioneer.py

to install:
1. download pyqg-0.3.0.tar.gz  from pypi
2. uncompress it
3. cd pyqg-0.3.0
3. copy the versioneer.py from https://github.com/pyqg/pyqg/blob/master/versioneer.py
4. install with "pip install ."

or just clone the repo and then install with "pip install ."

**Comment by rabernat** [comment]
Sorry for this problem. It is popping up everywhere, for example, see https://github.com/xgcm/xrft/issues/108 for the same problem in a different package. I think it is related to a change in python packaging that I don't fully understand.

**Comment by illtellyoulater** [comment]
I've encountered the same problem. I'm attaching the full output in case you need it for debugging:

```
INFO: pip is looking at multiple versions of opt-einsum to determine which version is compatible with other requirements. This could take a while.
  Using cached opt_einsum-2.1.3.tar.gz (49 kB)
  Using cached opt_einsum-2.1.2.tar.gz (49 kB)
  Using cached opt_einsum-2.1.1.tar.gz (33 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\myname\.conda\envs\my-conda-env\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\myname\\AppData\\Local\\Temp\\pip-install-5fd6pusa\\opt-einsum_338fdeedb22c43b5866a08f07894571e\\setup.py'"'"'; __file__='"'"'C:\\Users\\myname\\AppData\\Local\\Temp\\pip-install-5fd6pusa\\opt-einsum_338fdeedb22c43b5866a08f07894571e\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\myname\AppData\Local\Temp\pip-pip-egg-info-p1y25hoa'
         cwd: C:\Users\myname\AppData\Local\Temp\pip-install-5fd6pusa\opt-einsum_338fdeedb22c43b5866a08f07894571e\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\myname\AppData\Local\Temp\pip-install-5fd6pusa\opt-einsum_338fdeedb22c43b5866a08f07894571e\setup.py", line 12, in <module>
        version=versioneer.get_version(),
    AttributeError: module 'versioneer' has no attribute 'get_version'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/30/52/64ed28228334a1124c082809402c01c4219085c5ee0f34991ace24a10dad/opt_einsum-2.1.1.tar.gz#sha256=5d1b9ba61829dc35e30971a926e0c12a378009f58a1962c558e776908d27f0f8 (from https://pypi.org/simple/opt-einsum/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by asross** [comment]
This has been resolved by the removal of Versioneer in https://github.com/pyqg/pyqg/pull/278.
