### ISSUE TITLE
AttributeError: module 'pyqg' has no attribute 'QGModel'

### ISSUE THREAD

**Issue by QimengLiu** [pyqg/pyqg#219]
I run the Two Layer QG Model Example on pycharm or spider, but met one problem.There is an AttributeError: module 'pyqg' has no attribute 'QGModel'. I don't know why.
![image](https://user-images.githubusercontent.com/45824133/76195830-1d693400-6224-11ea-81bf-72603127d7d6.png)

**Comment by asross** [comment]
I know this is a very late response, but I'm guessing this was an install issue, which may be resolved by upstream changes!
