### ISSUE TITLE
add xarray attributes

### ISSUE THREAD

**Issue by hscannell** [pyqg/pyqg#235]
Some of the coordinate variables should be attributes. It should look like this:

**Coordinates**
k: 33
l: 64
lev: 2
x: 64
y: 64

**Attributes**
L: float64
W: float64
dt: timedelta64[ns]
filterfac: float64
nk: int64
nl: int64
ntd: int64
nx: int64
ny: int64
nz: int64
pmodes: int64
radii: int64
rek: float64
taveint: timedelta64[ns]
tavestart: timedelta64[ns]
tc: timedelta64[ns]
time: timedelta64[ns]
tmax: timedelta64[ns]
tsnapint: timedelta64[ns]
tsnapstart: timedelta64[ns]
twrite: int64

**Comment by rabernat** [comment]
We discussed this at the meeting today. We are ready for PR with this feature whenever you have the time.
