### ISSUE TITLE
Proposal for developer meeting

### ISSUE THREAD

**Issue by hscannell** [pyqg/pyqg#236]
@rabernat and I had the idea of organizing a meeting with pyqg contributors and active users to help coordinate efforts in improving the package going forward. We are excited by the recent interest and would like to open the dialogue for further enhancements. Pyqg has been a wonderful tool in my own research and I would be really excited to see it become more accessible to others. If you would like to participate in the meeting, please [select the times](https://whenisgood.net/2aarehe) that work for you and we'll go from there. Thanks!

... @MFJansen @cesar-rocha @jrbourbeau @tmachnitzki @mbueti @pittwolfe @jamesp @biavillasboas @TomNicholas

**Comment by rabernat** [comment]
Also @cmdupuis3!

**Comment by hscannell** [comment]
For those that entered their availability on the calendar, it look like everyone can make it on 
### Thursday, May 6, 2:00–3:00 PM ET

Below is the zoom link. See you then!
[https://columbiauniversity.zoom.us/j/96786860974](https://columbiauniversity.zoom.us/j/96786860974
)

**Comment by rabernat** [comment]
Thanks for organizing this Hillary!
