### ISSUE TITLE
refactor / improve diagnostics for xarray compatibility

### ISSUE THREAD

**Issue by rabernat** [pyqg/pyqg#238]
Our diagnostics allow for specifying units and description

https://github.com/pyqg/pyqg/blob/02e8e713660d6b2043410f2fef6a186a7cb225a6/pyqg/model.py#L611-L626

But these are not populated consistently. 

https://github.com/pyqg/pyqg/blob/02e8e713660d6b2043410f2fef6a186a7cb225a6/pyqg/model.py#L573-L576

We also need to add "dimensions" to the diagnostics metadata. This will give us everything we need to populate the xarray outputs for diagnostics:

https://github.com/pyqg/pyqg/blob/master/pyqg/xarray_output.py

TODO:
- [x] Update existing diagnostics to always provide units and description
- [x] Add dimensions to diagnostic metadata api
- [x] Update existing diagnostics to always provide dims
- [ ] Add a documentation page about diagnostics and how to create a custom diagnostic

**Comment by hscannell** [comment]
Some diagnostics are defined twice, for example `APEflux`:

https://github.com/pyqg/pyqg/blob/02e8e713660d6b2043410f2fef6a186a7cb225a6/pyqg/qg_model.py#L250-L255

https://github.com/pyqg/pyqg/blob/02e8e713660d6b2043410f2fef6a186a7cb225a6/pyqg/layered_model.py#L301-L304

Besides the functions looking different, some of the descriptions are inconsistent. Should I just leave this as is? i.e., is there a good reasons for the subtle difference that I'm not aware of?

**Comment by rabernat** [comment]
The diagnostics are different because the models are different. So I think this makes sense.

**Comment by hscannell** [comment]
great! OK, I'll leave it as is.

**Comment by hscannell** [comment]
ah, got it! I'll fix it.
