### ISSUE TITLE
Add units for diagnostic variables

### ISSUE THREAD

**Issue by hscannell** [pyqg/pyqg#248]
Currently units are left blank and it would be great if someone carefully review and populate these.

- [x] KEflux
- [x] KEspec_modal
- [x] KEflux_div
- [x] APEgenspec
- [x] APEgen
- [x] APEflux
- [x] APEspec
- [x] APEflux_div
- [x] PEspec_modal
- [x] entspec
- [x] ENSflux
- [x] ENSgenspec

**Comment by asross** [comment]
Resolved by https://github.com/pyqg/pyqg/pull/284.
