### ISSUE TITLE
Helper tools for downscaling simulations / recomputing diagnostics

### ISSUE THREAD

**Issue by asross** [pyqg/pyqg#253]
I'm interested in evaluating whether particular sets of low-resolution and high-resolution simulation runs have similar statistical properties. One natural way to test this is to extract the same diagnostics from both low-dimensional and high-dimensional simulations, but downscale the higher-dimensional simulations first (according to some filtering and coarse-graining procedure). Afterwards, distributions can be fit to each set of diagnostics, and then distributional difference metrics can be computed (e.g. KL).

Currently, the process of downscaling a pyqg simulation's diagnostics is a little bit tricky, and I'm not sure if it's actually possible to do directly from quantities in frequency space. My strategy instead is something like the following:

```python
m1 = pyqg.QGModel(nx=256, **params)
m1.run()

def downscale(q, scale=4):
    filter = gcm_filters.Filter(filter_scale=scale, dx_min=1, grid_type=gcm_filters.GridType.REGULAR)
    return filter.apply(q, dims=['y','x']).coarsen(x=scale, y=scale).mean()

m2 = pyqg.QGModel(nx=64, **params)
m2.set_q1q2(*downscale(m1.to_dataset().q.isel(time=0)))
m2._step_forward() # takes an extra timestep but gets us reasonably close diagnostics;
                   # could instead call a bunch of private methods here

original_res_diagnostics = m1.diagnostics
downscaled_diagnostics = m2.diagnostics
```

This feels pretty hacky overall, and also slightly wrong. It would be cool instead if it were possible to filter/coarsen the simulation as a first-class method, e.g. by being able to write

```python
m1 = pyqg.QGModel(nx=256, **params)
m1.run()

filter = gcm_filters.Filter(filter_scale=scale, dx_min=1, grid_type=gcm_filters.GridType.REGULAR)
m2 = m1.filter(filter).coarsen(x=4, y=4).mean()
```

Does this seem like an issue worth addressing in code?

**Comment by rabernat** [comment]
Did you perhaps intend to post this in the gcm-filters issue tracker (rather than pyqg)? 😄

**Comment by asross** [comment]
I don't think so! No changes to `gcm-filters` would be required for this type of feature, only to `pyqg` -- e.g. something like

```
def filter(self, filter):
   self.set_q1q2(*filter.apply(self.to_dataset().q))
   self._invert()
```

**Comment by rabernat** [comment]
Ok understood, thanks for explaining.

I'm not sure that filtering / downscaling is something we want to explicitly support in the pyqg API. Ideally we could just interoperate well with other packages. Could you flesh out a bit more in words what the `filter` function defined above should do? Is it really about filtering specifically or is it more general, about updating the model state _somehow_ and then re-calculating all the diagnostics? If the later, I would be much more inclined to support it.

Overall I am wary about adding new features because this package is way under-maintained. All of the original developers but me have left the project (most moved to Julia). If we could find a way to start tackling the issue and PR backlog, I would be much more inclined to start adding features.

**Comment by asross** [comment]
Understood about the wariness of adding new features! For this one, it's the latter, though -- updating the state of the model and then recomputing all downstream variables, including diagnostics (at least for the current timestep).

Although propagating potential vorticity changes to other variables seems straightforward, updating the resolution of the model seems more difficult. Perhaps it makes sense to keep most of this feature as code external to the simulation, but instead offer an interface to invoke/consolidate some methods which are currently private.

Just to make things really concrete, to get the full functionality I'm looking for (a downscaled version of a high-resolution run), I currently have to do something like this:

```python
# create a (relatively) high resolution model
hires = pyqg.QGModel(nx=256, **kwargs)

# create a low resolution model with the same parameters as the high resolution model
lores = pyqg.QGModel(nx=64, **kwargs)

# create a filter
filter = gcm_filters.Filter(filter_scale=4, dx_min=1, grid_type=gcm_filters.GridType.REGULAR)

# take snapshots at every diagnostic computation interval
for t in hires.run_with_snapshots(tsnapstart=hires.tavestart, tsnapint=hires.taveint):
    # copy over the high resolution model's state, except for time which is not writable
    # (hopefully this is everything we need to do)
    lores.set_q1q2(*filter.apply(hires.to_dataset().q, ['y','x']).coarsen(x=4, y=4).mean().data[0])

    # recompute downstream variables
    # (hopefully this is everything we need to do)
    lores._invert()
    lores._increment_diagnostics()

    # save the models
    hires_dataset = hires.to_dataset()
    lores_dataset = lores.to_dataset().assign_coords(time=np.array([t]))
    lores_dataset.to_netcdf(f"lores_model_at_time_{hires.t}.nc")
    hires_dataset.to_netcdf(f"hires_model_at_time_{hires.t}.nc")
```

Maybe this is fine, though (despite the private method calls), and feel free to close this issue if so!
