### ISSUE TITLE
Update packaging

### ISSUE THREAD

**Issue by rabernat** [pyqg/pyqg#255]
pyqg packaging and release procedure is very old. Ideally we should
- [x] drop python 2.7 support
- [x] move to setuptools_scm-style packaging
- [x] create a GitHub workflow for releasing

**Comment by hugovk** [comment]
Please see PR https://github.com/pyqg/pyqg/pull/258 to drop Python 2.7.

**Comment by rabernat** [comment]
Closed by #258

**Comment by hugovk** [comment]
https://github.com/pyqg/pyqg/pull/258 only addressed the first checkbox, not the other two.
