### ISSUE TITLE
Error in kernel.pyx, line 224

### ISSUE THREAD

**Issue by dante831** [pyqg/pyqg#271]
The 2-layer QG model [example](https://pyqg.readthedocs.io/en/latest/examples/two-layer.html) cannot be run with a different number of grids in x and y directions. The problem lies in line 224 in kernel.pyx that it defines an empty field as: `shape = (self.nz, self.ny, self.ny)`. 

It should really be `shape = (self.nz, self.ny, self.nx)`. Please consider changing it. Thanks.

**Comment by rabernat** [comment]
Sorry for the very slow reply to this. I have opened #279 to fix this.
