### ISSUE TITLE
Continued issues with `calc_ispec`

### ISSUE THREAD

**Issue by asross** [pyqg/pyqg#275]
Per discussions with @Pperezhogin, we think there might still be errors in the [`calc_ispec`](https://github.com/pyqg/pyqg/blob/723d94ad1573dcf28a134dd6fb49fa966f8ef41a/pyqg/diagnostic_tools.py#L52-L85) helper (even after [my PR](https://github.com/pyqg/pyqg/pull/273) which attempted to address [a more glaring issue](https://github.com/pyqg/pyqg/issues/272)). However, we're not totally sure how to fix it in a way that fits the other requirements of the library, and especially how to create a good unit test to verify it. This is a pretty important issue for us to fix, however, since other analyses depend on it.

Specific issues we've been discussing include:
- the minimum radial wavenumber probably should be `min(dk, dl)` rather than 1.5x (its current value) or 0.5x (its previous value)
- the normalization factor defined [here](https://github.com/pyqg/pyqg/pull/273) might be incorrect, and it seems like we should be instead using the Parseval identity (correct me if I'm mischaracterizing this @Pperezhogin)
- there might be double-counting of quantities at particular wavenumbers, potentially because [the intervals we sum over](https://github.com/pyqg/pyqg/blob/723d94ad1573dcf28a134dd6fb49fa966f8ef41a/pyqg/diagnostic_tools.py#L81) might not be closed (due to the `<=` rather than `<`) and potentially because we might not be handling the `k` and `l` difference (i.e. some with complex conjugates, some unique) correctly, though this is a bit outside of my area of familiarity

So, just wanted to bring this issue up and see if anyone has thoughts on how to fix it -- ideally with a unit test with some complex array where we have ground-truth knowledge about the complete isotropic spectrum and can verify that this method returns it.

**Comment by rabernat** [comment]
Thanks for raising this issue Andrew! The isotropic spectral diagnostics were originally implemented by @cesar-rocha, who is no longer really involved in this project.

In our spectral analysis package, we have an "isotropize" routine which may be a useful reference here

https://github.com/xgcm/xrft/blob/023c86e4e3c8d331604ab7ec1027f04bcf7ae0eb/xrft/xrft.py#L996-L1052

**Comment by rabernat** [comment]
Also related:
- https://github.com/xgcm/xrft/issues/145

**Comment by MFJansen** [comment]
A couple of quick comments on this:
I think there is no ideal way to compute a radial spectrum from spectral data that's on a (non-radial) k-l grid - inevitably (particularly at low wavenumbers) the number of data points in each spectral "ring" will not scale exactly with k_r (as it would in the limit of an infinitesimal k-l grid).
As a result, I think there are two reasonable options that both have advantages and disadvantages: 1) sum up energies from all spectral grid points in each ring or 2) average the energies across each spectral ring (then multiply by circumference or area of ring, depending on desired normalization/dimensions). Method (1) has the advantage that the energy will sum up to the correct total energy (as expected from Parseval) but the disadvantage that the spectrum may be quite noisy (particularly at low wavenumbers) due to varying numbers of (spectral) gridpoints. The opposite is the case for method (2).
What's currently implemented seems to be following Method 2 (which I personally think is preferable for most applications), although I'm not quite following l. 82, which I would have thought should be dth = 2*pi / fkr.sum() (although I may be missing something).
When using method 1 it would be important to change one of the <= or >= to a < or > to avoid double counting. With method 2 I think either is fine.
What the minimum and maximum wavenumbers should be is also arguably a matter of preference/application. In any case, I think the spectrum should be handled with care at low wavenumbers due to the problem discussed above, as well as for wavenumbers higher than the lower Nyquist frequency, due to the issue discussed in the xgcm issue linked by @rabernat.

**Comment by Pperezhogin** [comment]
I propose the following code:
```python
def calc_ispec(model, _var_dens, averaging = True, truncate=True, nd_wavenumber=False, nfactor = 1):
    """Compute isotropic spectrum `phr` from 2D spectrum of variable signal2d.

    Parameters
    ----------
    model : pyqg.Model instance
        The model object from which `var_dens` originates
    
    var_dens : squared modulus of fourier coefficients like this:
        np.abs(signal2d_fft)**2/m.M**2

    averaging: If True, spectral density is estimated with averaging over circles,
        otherwise summation is used and Parseval identity holds

    truncate: If True, maximum wavenumber corresponds to inner circle in Fourier space,
        otherwise - outer circle
    
    nd_wavenumber: If True, wavenumber is nondimensional: 
        minimum wavenumber is 1 and corresponds to domain length/width,
        otherwise - wavenumber is dimensional [m^-1]

    nfactor: width of the bin in sqrt(dk^2+dl^2) units

    Returns
    -------
    kr : array
        isotropic wavenumber
    phr : array
        isotropic spectrum

    Normalization:
    signal2d.var() = phr.sum() * (kr[1] - kr[0])
    """

    # account for complex conjugate
    var_dens = np.copy(_var_dens)
    var_dens[...,0] /= 2
    var_dens[...,-1] /= 2

    if truncate:
        kmax = np.minimum(model.ll.max(), model.kk.max())
    else:
        kmax = np.sqrt((model.ll.max())**2 + (model.kk.max())**2)
    
    kmin = np.minimum(model.dk, model.dl)

    dkr = np.sqrt(model.dk**2 + model.dl**2) * nfactor

    # left border of bins
    kr = np.arange(kmin, kmax+dkr, dkr)
    
    phr = np.zeros(kr.size)

    for i in range(kr.size):
        if averaging:
            fkr =  (model.wv>=kr[i]) & (model.wv<=kr[i]+dkr)    
            if fkr.sum() == 0:
                phr[i] = 0.
            else:
                phr[i] = var_dens[fkr].mean() * (kr[i]+dkr/2) * pi / (model.dk * model.dl)
        else:
            fkr =  (model.wv>=kr[i]) & (model.wv<kr[i]+dkr)
            phr[i] = var_dens[fkr].sum() / dkr
    
    # convert left border of the bin to center
    kr = kr + dkr/2

    # convert to non-dimensional wavenumber 
    # preserving integral over spectrum
    if nd_wavenumber:
        kr = kr / kmin
        phr = phr * kmin

    return kr, phr
```

**What code do**

Let we have 2d array `u`. 
The function takes:
`np.abs(u_fft)**2/m.M**2`
Returns:
Isotropic spectrum with normalization `u.var()/2 = phr.sum()*(kr[1]-kr[0])`

**Features**

- Power density can be estimated in two ways: averaging over circles or summation
- Maximum wavenumber can correspond to inner or outer circle in Fourier plane
- Wavenumbers can be nondimensional or dimensional
- Default parameters correspond to the old algorithm, but with some fixes

**In averaging mode (i.e. default) the proposed code differs from the old one in the following**
- Specific normalization of inputs is assumed
- Normalization of outputs is such that to (approximately) satisfy Parseval Identity
- Complex conjugates within half-plane are accounted: `var_dens[...,0] /= 2; var_dens[...,-1] /= 2`
- Minimum wavenumber for bins corresponds to the domain length `kmin = np.minimum(model.dk, model.dl)`
- Biased averaging `1/ (fkr.sum()-1)` is changed to unbiased `var_dens[fkr].mean()`
- To satisfy Parseval Identity, normalization `1/(model.dk * model.dl)` is introduced

**Results compared to the old code**
For averaging and summation algorithms, results are similar and close to the old code
up to normalization constant `2e+10`
![image](https://user-images.githubusercontent.com/35234405/150889530-47ef5e1a-4098-4a7a-a1d2-03a702515c0e.png)

**Energy spectrum for the proposed code with different parameters**
- The shape of the curve is stable w.r.t. the algorithm (averaging/summation) and bin size
- Parseval identity holds exactly for summation algorithm without truncation of wavenumbers
![image](https://user-images.githubusercontent.com/35234405/150889810-c58b4dbf-2596-4ca3-aed9-8f244104c6f9.png)

**Subgrid forces power spectrum**
Almost half of the power density corresponds to the corners of Fourier plane. Only `averaging=False,truncation=False` algorithm can estimate power density.
![image](https://user-images.githubusercontent.com/35234405/150890130-a7a4ffb6-5eb9-4284-9f3f-d9786055dbe2.png)

**Discussion**
- Averaging and summation algorithms give curves of comparable smoothness
- Smoothness is controled by the bin width
- Summation algorithm is preferable in corners of Fourier space
- Increasing bin width, lower wavenumber increases (to make estimation unbiased)
- I did not managed to construct an unbiased estimate of the power spectrum in the minimum wavenumber (1 in N/D units)
- In `truncate=False` mode chess-board harmonic makes estimated density discontinous. May be it is better to discard it.

**Why Parseval identity is important?**
- Without satisfying this identity, the normalization and physical dimensionality of output as well as coverage of Fourier space are unclear.
- The proposed normalization of outputs allows to plot Kolmogorov/Kraichnan spectra and place clear physical dimensionality for power spectrum on the figures.
![image](https://user-images.githubusercontent.com/35234405/150891858-bbc7cde2-b08a-4765-a4a0-8aa7fdda6ee0.png)

**Comment by MFJansen** [comment]
Looks good to me! Would you mind putting together a PR?
Thank you!

**Comment by MFJansen** [comment]
Good question about input. I'm guessing the expected input is probably the 2D spectrum as computed by the model's diagnostic  ([here](https://github.com/pyqg/pyqg/blob/723d94ad1573dcf28a134dd6fb49fa966f8ef41a/pyqg/model.py#L610))?
