### ISSUE TITLE
plotting final stopping time

### ISSUE THREAD

**Issue by francispoulin** [pyqg/pyqg#68]
When I modified the sqg script I noticed that if I choose tmax to be 26.0, it would not plot the solution at 26.  I changed it to 26.005 and then it plotted it. This is not a big deal but thought I would mention it.

**Comment by rabernat** [comment]
Yes, I agree that this is a bug. At the very least, it is confusing.

I think it comes from a mismatch between when the output is written and when the timestep is incremented.
