### ISSUE TITLE
Typos in sqg example in documentation

### ISSUE THREAD

**Issue by rabernat** [pyqg/pyqg#69]
There is a typo in @francispoulin's new sqg documentation which I didn't catch while reviewing the pull request #67. 

http://pyqg.readthedocs.org/en/latest/examples/sqg.html

Right after the second equation, there is some text that is formatted as math.

**Comment by francispoulin** [comment]
Not sure where to put this comment so here it is.
Thanks for the help in cleaning things up.  I am slowing figuring this thing out.
I decided to separate the equations in different boxes and the html I produced looked good.  Please let me know if you agree, or not.

**Comment by rabernat** [comment]
Closed by #70
