### ISSUE TITLE
tavestart

### ISSUE THREAD

**Issue by crocha700** [pyqg/pyqg#75]
*tavestart* is supposed to be the time at which the model start computing averages for the diagnostics, but it is never used in model.py. Here's what _calc_diagnostic does:
~~~~{.python}
if (self.t>=self.dt) and (self.tc%self.taveints==0):
       self._increment_diagnostics()

(...)
~~~~

is *tavestart* used elsewhere?

 (I think we're missing a self.t>=self.tavestart above).

**Comment by rabernat** [comment]
I wonder how far back this goes. Most of this logic can be traced back to Malte's original code.

Anyway, obviously a bug, and easily fixed. Are you going to do it?

**Comment by MFJansen** [comment]
I believe it happened on March 28: 
https://github.com/pyqg/pyqg/commit/26f9111dfef89c3cdd1e8121e9ba226254d336b3#diff-c6c9f6600ccc812b2e7038316e6eff8e

I assume this was an accidental edit?

**Comment by rabernat** [comment]
You're busted @crocha700! :stuck_out_tongue_closed_eyes:

**Comment by crocha700** [comment]
Thanks for digging that @MFJansen. This was likely an accidental edit. My bad: unfortunately that commit is very non specific – too many changes in a single commit... I just submitted a PR fixing it.

I also fixed in my brach multi_layer which I'm going to merge into develop latter today.
