### ISSUE TITLE
change license

### ISSUE THREAD

**Issue by rabernat** [pyqg/pyqg#76]
We picked GPL somewhat randomly. Apparently it is not the best choice for a science application:
https://twitter.com/wesmckinn/status/651009426879594496

Some good advice here:
http://www.astrobetter.com/blog/2014/03/10/the-whys-and-hows-of-licensing-scientific-code/

**Comment by crocha700** [comment]
Looks like new BSD will suit us most.

**Comment by crocha700** [comment]
http://choosealicense.com

**Comment by rabernat** [comment]
Lets to MIT then, for obvious reasons :wink:
