### ISSUE TITLE
Add documentation for diagnostics in two-layer model

### ISSUE THREAD

**Issue by crocha700** [pyqg/pyqg#84]
Why do we take the negative sign of the diagnostics before plotting? 

http://pyqg.readthedocs.org/en/stable/examples/two-layer.html#plot-diagnostics

**Comment by crocha700** [comment]
I added some stuff into develop /docs/equations/layered.rst

**Comment by rabernat** [comment]
So is this closed?

**Comment by crocha700** [comment]
Yes. The layered model docs will have a description of the diagnostics: http://pyqg.readthedocs.org/en/develop/equations/notation_layered_model.html

(I'm working on refactoring the notebook into a tex file that will then be converted into .rst
[layered.pdf](https://github.com/pyqg/pyqg/files/17312/layered.pdf)
)
