### ISSUE TITLE
Write equations part of the  docs directly in latex

### ISSUE THREAD

**Issue by crocha700** [pyqg/pyqg#88]
The notebook TeX support is still poor. In particular, we may want number the equations, cross-reference equations, define new commands, etc. We can use [pandoc](http://pandoc.org/installing.html) to convert the tex files into rst.

**Comment by rabernat** [comment]
If you can figure out how to make this work with readthedocs, it's fine with me.

**Comment by crocha700** [comment]
As I said in #103, one can write the equations part of the docs in latex  and then convert into ```rst``` using [pandoc](http://pandoc.org):

```{bash}
$ pandoc -f latex notation_xx.tex -t rst > notation_xx.rst
```
Writing the equations in a notebook and then converting it to ```rst``` using ```ipython nbconvert``` still works.

**Comment by francispoulin** [comment]
I am now looking at the rst in my browser using chrome and for some reason it doesn't look like the equations.  I see the latex.  Firefox says the same thing.   

https://github.com/crocha700/pyqg/blob/layered/docs/equations/notation_layered.rst

Two questions:
1) Does one need to do something special to your browser to make it look like equations?
2) How do you advise we open rst's on a mac?

Thanks.

**Comment by crocha700** [comment]
You can read it in the *latest* version of the [docs](http://pyqg.readthedocs.org/en/latest/equations/notation_layered.html)

It is true that github renders notebook, so people can always look at the docs directly in the repo. We can also push the pdf file, which is also rendered by github.

**Comment by francispoulin** [comment]
Ah, sorry for not looking at the latest version. That does look much better.

Thanks.
